// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pierce;

#nullable disable

namespace Pierce.Migrations
{
    [DbContext(typeof(PierceContext))]
    [Migration("20241230051411_ForeignKeyRelations")]
    partial class ForeignKeyRelations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.7");

            modelBuilder.Entity("Pierce.Article", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Categories")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("categories");

                    b.Property<string>("CommentLink")
                        .HasColumnType("TEXT")
                        .HasColumnName("comment_link");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<long>("FeedId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("feed_id");

                    b.Property<string>("Link")
                        .HasColumnType("TEXT")
                        .HasColumnName("link");

                    b.Property<DateTime>("PublishDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("publish_date");

                    b.Property<string>("Summary")
                        .HasColumnType("TEXT")
                        .HasColumnName("summary");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("title");

                    b.Property<string>("UniqueId")
                        .HasColumnType("TEXT")
                        .HasColumnName("unique_id");

                    b.HasKey("Id")
                        .HasName("pk_articles");

                    b.HasIndex("FeedId", "PublishDate")
                        .HasDatabaseName("ix_articles_feed_id_publish_date");

                    b.ToTable("articles", (string)null);
                });

            modelBuilder.Entity("Pierce.Feed", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("ArticleCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("article_count");

                    b.Property<string>("Categories")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("categories");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<int>("Errors")
                        .HasColumnType("INTEGER")
                        .HasColumnName("errors");

                    b.Property<string>("IconUri")
                        .HasColumnType("TEXT")
                        .HasColumnName("icon_uri");

                    b.Property<string>("ImageLinkTarget")
                        .HasColumnType("TEXT")
                        .HasColumnName("image_link_target");

                    b.Property<string>("ImageTitle")
                        .HasColumnType("TEXT")
                        .HasColumnName("image_title");

                    b.Property<DateTime>("LastRead")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_read");

                    b.Property<string>("Link")
                        .HasColumnType("TEXT")
                        .HasColumnName("link");

                    b.Property<string>("LogoUri")
                        .HasColumnType("TEXT")
                        .HasColumnName("logo_uri");

                    b.Property<DateTime>("NextRead")
                        .HasColumnType("TEXT")
                        .HasColumnName("next_read");

                    b.Property<TimeSpan>("ReadInterval")
                        .HasColumnType("TEXT")
                        .HasColumnName("read_interval");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("title");

                    b.Property<string>("Uri")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("uri");

                    b.HasKey("Id")
                        .HasName("pk_feeds");

                    b.HasIndex("Uri")
                        .IsUnique()
                        .HasDatabaseName("ix_feeds_uri");

                    b.ToTable("feeds", (string)null);
                });

            modelBuilder.Entity("Pierce.Subscription", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<long>("FeedId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("feed_id");

                    b.Property<TimeSpan>("Interval")
                        .HasColumnType("TEXT")
                        .HasColumnName("interval");

                    b.Property<long>("UserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_subscriptions");

                    b.HasIndex("FeedId")
                        .HasDatabaseName("ix_subscriptions_feed_id");

                    b.HasIndex("UserId", "FeedId")
                        .IsUnique()
                        .HasDatabaseName("ix_subscriptions_user_id_feed_id");

                    b.ToTable("subscriptions", (string)null);
                });

            modelBuilder.Entity("Pierce.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("email");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("password_hash");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Pierce.Article", b =>
                {
                    b.HasOne("Pierce.Feed", "Feed")
                        .WithMany("Articles")
                        .HasForeignKey("FeedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_articles_feeds_feed_id");

                    b.OwnsOne("Pierce.AuthorInfo", "AuthorInfo", b1 =>
                        {
                            b1.Property<long>("ArticleId")
                                .HasColumnType("INTEGER");

                            b1.HasKey("ArticleId")
                                .HasName("pk_articles");

                            b1.ToTable("articles");

                            b1.ToJson("author_info");

                            b1.WithOwner()
                                .HasForeignKey("ArticleId")
                                .HasConstraintName("fk_articles_articles_article_id");

                            b1.OwnsMany("Pierce.Author", "Authors", b2 =>
                                {
                                    b2.Property<long>("AuthorInfoArticleId")
                                        .HasColumnType("INTEGER");

                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAddOrUpdate()
                                        .HasColumnType("INTEGER");

                                    b2.Property<string>("Email")
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Link")
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Name")
                                        .IsRequired()
                                        .HasColumnType("TEXT");

                                    b2.HasKey("AuthorInfoArticleId", "Id");

                                    b2.ToTable("articles");

                                    b2.ToJson("author_info");

                                    b2.WithOwner()
                                        .HasForeignKey("AuthorInfoArticleId")
                                        .HasConstraintName("fk_articles_articles_author_info_article_id");
                                });

                            b1.Navigation("Authors");
                        });

                    b.Navigation("AuthorInfo")
                        .IsRequired();

                    b.Navigation("Feed");
                });

            modelBuilder.Entity("Pierce.Feed", b =>
                {
                    b.OwnsOne("Pierce.AuthorInfo", "AuthorInfo", b1 =>
                        {
                            b1.Property<long>("FeedId")
                                .HasColumnType("INTEGER");

                            b1.HasKey("FeedId");

                            b1.ToTable("feeds");

                            b1.ToJson("author_info");

                            b1.WithOwner()
                                .HasForeignKey("FeedId")
                                .HasConstraintName("fk_feeds_feeds_id");

                            b1.OwnsMany("Pierce.Author", "Authors", b2 =>
                                {
                                    b2.Property<long>("AuthorInfoFeedId")
                                        .HasColumnType("INTEGER");

                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAddOrUpdate()
                                        .HasColumnType("INTEGER");

                                    b2.Property<string>("Email")
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Link")
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Name")
                                        .IsRequired()
                                        .HasColumnType("TEXT");

                                    b2.HasKey("AuthorInfoFeedId", "Id");

                                    b2.ToTable("feeds");

                                    b2.ToJson("author_info");

                                    b2.WithOwner()
                                        .HasForeignKey("AuthorInfoFeedId")
                                        .HasConstraintName("fk_feeds_feeds_author_info_feed_id");
                                });

                            b1.Navigation("Authors");
                        });

                    b.Navigation("AuthorInfo")
                        .IsRequired();
                });

            modelBuilder.Entity("Pierce.Subscription", b =>
                {
                    b.HasOne("Pierce.Feed", "Feed")
                        .WithMany("Subscriptions")
                        .HasForeignKey("FeedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_subscriptions_feeds_feed_id");

                    b.HasOne("Pierce.User", "User")
                        .WithMany("Subscriptions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_subscriptions_users_user_id");

                    b.Navigation("Feed");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Pierce.Feed", b =>
                {
                    b.Navigation("Articles");

                    b.Navigation("Subscriptions");
                });

            modelBuilder.Entity("Pierce.User", b =>
                {
                    b.Navigation("Subscriptions");
                });
#pragma warning restore 612, 618
        }
    }
}
